# Generated by Django 5.2.17 on 2026-09-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
